//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpsonsWeb.SimpsonServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Character", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Character : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SimpsonServiceReference.SimpsonsServiceSoap")]
    public interface SimpsonsServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllCharactersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCharacters", ReplyAction="*")]
        SimpsonsWeb.SimpsonServiceReference.GetAllCharactersResponse GetAllCharacters(SimpsonsWeb.SimpsonServiceReference.GetAllCharactersRequest request);
        
        // CODEGEN: Generating message contract since element name lastName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchByLastName", ReplyAction="*")]
        SimpsonsWeb.SimpsonServiceReference.SearchByLastNameResponse SearchByLastName(SimpsonsWeb.SimpsonServiceReference.SearchByLastNameRequest request);
        
        // CODEGEN: Generating message contract since element name HelloResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Hello", ReplyAction="*")]
        SimpsonsWeb.SimpsonServiceReference.HelloResponse Hello(SimpsonsWeb.SimpsonServiceReference.HelloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCharactersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCharacters", Namespace="http://tempuri.org/", Order=0)]
        public SimpsonsWeb.SimpsonServiceReference.GetAllCharactersRequestBody Body;
        
        public GetAllCharactersRequest() {
        }
        
        public GetAllCharactersRequest(SimpsonsWeb.SimpsonServiceReference.GetAllCharactersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCharactersRequestBody {
        
        public GetAllCharactersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCharactersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCharactersResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimpsonsWeb.SimpsonServiceReference.GetAllCharactersResponseBody Body;
        
        public GetAllCharactersResponse() {
        }
        
        public GetAllCharactersResponse(SimpsonsWeb.SimpsonServiceReference.GetAllCharactersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCharactersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimpsonsWeb.SimpsonServiceReference.Character[] GetAllCharactersResult;
        
        public GetAllCharactersResponseBody() {
        }
        
        public GetAllCharactersResponseBody(SimpsonsWeb.SimpsonServiceReference.Character[] GetAllCharactersResult) {
            this.GetAllCharactersResult = GetAllCharactersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByLastNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByLastName", Namespace="http://tempuri.org/", Order=0)]
        public SimpsonsWeb.SimpsonServiceReference.SearchByLastNameRequestBody Body;
        
        public SearchByLastNameRequest() {
        }
        
        public SearchByLastNameRequest(SimpsonsWeb.SimpsonServiceReference.SearchByLastNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByLastNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lastName;
        
        public SearchByLastNameRequestBody() {
        }
        
        public SearchByLastNameRequestBody(string lastName) {
            this.lastName = lastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByLastNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByLastNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimpsonsWeb.SimpsonServiceReference.SearchByLastNameResponseBody Body;
        
        public SearchByLastNameResponse() {
        }
        
        public SearchByLastNameResponse(SimpsonsWeb.SimpsonServiceReference.SearchByLastNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByLastNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimpsonsWeb.SimpsonServiceReference.Character[] SearchByLastNameResult;
        
        public SearchByLastNameResponseBody() {
        }
        
        public SearchByLastNameResponseBody(SimpsonsWeb.SimpsonServiceReference.Character[] SearchByLastNameResult) {
            this.SearchByLastNameResult = SearchByLastNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Hello", Namespace="http://tempuri.org/", Order=0)]
        public SimpsonsWeb.SimpsonServiceReference.HelloRequestBody Body;
        
        public HelloRequest() {
        }
        
        public HelloRequest(SimpsonsWeb.SimpsonServiceReference.HelloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloRequestBody {
        
        public HelloRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimpsonsWeb.SimpsonServiceReference.HelloResponseBody Body;
        
        public HelloResponse() {
        }
        
        public HelloResponse(SimpsonsWeb.SimpsonServiceReference.HelloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloResult;
        
        public HelloResponseBody() {
        }
        
        public HelloResponseBody(string HelloResult) {
            this.HelloResult = HelloResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimpsonsServiceSoapChannel : SimpsonsWeb.SimpsonServiceReference.SimpsonsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpsonsServiceSoapClient : System.ServiceModel.ClientBase<SimpsonsWeb.SimpsonServiceReference.SimpsonsServiceSoap>, SimpsonsWeb.SimpsonServiceReference.SimpsonsServiceSoap {
        
        public SimpsonsServiceSoapClient() {
        }
        
        public SimpsonsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpsonsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpsonsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpsonsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpsonsWeb.SimpsonServiceReference.GetAllCharactersResponse SimpsonsWeb.SimpsonServiceReference.SimpsonsServiceSoap.GetAllCharacters(SimpsonsWeb.SimpsonServiceReference.GetAllCharactersRequest request) {
            return base.Channel.GetAllCharacters(request);
        }
        
        public SimpsonsWeb.SimpsonServiceReference.Character[] GetAllCharacters() {
            SimpsonsWeb.SimpsonServiceReference.GetAllCharactersRequest inValue = new SimpsonsWeb.SimpsonServiceReference.GetAllCharactersRequest();
            inValue.Body = new SimpsonsWeb.SimpsonServiceReference.GetAllCharactersRequestBody();
            SimpsonsWeb.SimpsonServiceReference.GetAllCharactersResponse retVal = ((SimpsonsWeb.SimpsonServiceReference.SimpsonsServiceSoap)(this)).GetAllCharacters(inValue);
            return retVal.Body.GetAllCharactersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpsonsWeb.SimpsonServiceReference.SearchByLastNameResponse SimpsonsWeb.SimpsonServiceReference.SimpsonsServiceSoap.SearchByLastName(SimpsonsWeb.SimpsonServiceReference.SearchByLastNameRequest request) {
            return base.Channel.SearchByLastName(request);
        }
        
        public SimpsonsWeb.SimpsonServiceReference.Character[] SearchByLastName(string lastName) {
            SimpsonsWeb.SimpsonServiceReference.SearchByLastNameRequest inValue = new SimpsonsWeb.SimpsonServiceReference.SearchByLastNameRequest();
            inValue.Body = new SimpsonsWeb.SimpsonServiceReference.SearchByLastNameRequestBody();
            inValue.Body.lastName = lastName;
            SimpsonsWeb.SimpsonServiceReference.SearchByLastNameResponse retVal = ((SimpsonsWeb.SimpsonServiceReference.SimpsonsServiceSoap)(this)).SearchByLastName(inValue);
            return retVal.Body.SearchByLastNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpsonsWeb.SimpsonServiceReference.HelloResponse SimpsonsWeb.SimpsonServiceReference.SimpsonsServiceSoap.Hello(SimpsonsWeb.SimpsonServiceReference.HelloRequest request) {
            return base.Channel.Hello(request);
        }
        
        public string Hello() {
            SimpsonsWeb.SimpsonServiceReference.HelloRequest inValue = new SimpsonsWeb.SimpsonServiceReference.HelloRequest();
            inValue.Body = new SimpsonsWeb.SimpsonServiceReference.HelloRequestBody();
            SimpsonsWeb.SimpsonServiceReference.HelloResponse retVal = ((SimpsonsWeb.SimpsonServiceReference.SimpsonsServiceSoap)(this)).Hello(inValue);
            return retVal.Body.HelloResult;
        }
    }
}
